name: Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      FULL_NAME: "Gapilov Denis Nikolaevich"
      GROUP_NUMBER: "M3119"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print information
        run: |
          echo "Full Name: ${{ env.FULL_NAME }}"
          echo "Group Name: ${{ env.GROUP_NUMBER }}"
          echo "Nickname Github: ${{ github.actor }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --ignore=F401 .

      - name: Run unit tests
        run: |
          python -m unittest discover -s unit_tests -p "test_*.py"
