name: Tests Workflow

on:
  push:
    branches:
      - main
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FULL_NAME: "Gapilov Denis Nikolaevich"
      GROUP_NUMBER: "M3119"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --ignore=F401 .
